analyzer:
  exclude:
    - build/**
    - web/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enforce consistent naming
    always_declare_return_types: true
    avoid_unused_constructor_parameters: true
    # Accessibility
    use_full_hex_values_for_flutter_colors: true
    # Prefer const
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
