-- migration: 0003_storage.sql
-- ─────────────────────────────────────────────────────────────────────────
-- Creates the 'bill-images' private storage bucket.
--
-- Policy: users can only access their own files.
-- Path convention: {user_id}/{bill_id}/{filename}
--
-- The AI service uses a signed URL (generated by SupabaseService.
-- getSignedImageUrl) — it never holds the service key in the client.
-- ─────────────────────────────────────────────────────────────────────────

-- ── Bucket ────────────────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'bill-images',
  'bill-images',
  FALSE,          -- private — no public URLs
  52428800,       -- 50 MiB
  ARRAY[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/heic',
    'image/heif',
    'application/pdf'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- ── Storage RLS policies ──────────────────────────────────────────────────
-- Supabase storage policies live in the storage schema.
-- The path format: {user_id}/{bill_id}/{filename}
-- We extract the first segment (user_id) and compare to auth.uid().

-- SELECT — owner only
CREATE POLICY "owner can select own images"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'bill-images'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

-- INSERT — owner only, into their own folder
CREATE POLICY "owner can insert own images"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'bill-images'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

-- UPDATE — owner only
CREATE POLICY "owner can update own images"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'bill-images'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );

-- DELETE — owner only
CREATE POLICY "owner can delete own images"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'bill-images'
    AND (storage.foldername(name))[1] = auth.uid()::TEXT
  );
